language: python
python:
    - 3.4
    - 3.5
    - 3.6

env:
    - DJANGO='django>=1.10,<1.11'
    - DJANGO='django>=1.11,<2.0'
    - DJANGO='django>=2.0'

install:
    - travis_retry pip install $DJANGO
    - travis_retry pip install -r requirements.txt

script:
    - python manage.py test

#branches:
#    only:
#        - master

